language: python

before_install:
 - sudo apt-get update
 - sudo apt-get install build-essential python-dev python-numpy
 - sudo apt-get install libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev python-tk
 - git clone https://github.com/Itseez/opencv.git
 - cd opencv
 - mkdir build
 - cd build
 - cmake ..
 - make -j4
 - sudo make -j4 install
install:
  - "pip install --pre -r test/requirements.txt"
  - "python setup.py install"

python:
  - "2.7"
script:
  - bash test/runtest.sh
